# Generated by Django 3.1.4 on 2021-03-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210306_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userempid',
            name='emp_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
