# Generated by Django 3.1.4 on 2021-03-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210306_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgsiexam',
            name='answer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lgsiexam',
            name='examtype',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='lgsiexam',
            name='question',
            field=models.CharField(default='', max_length=500),
        ),
    ]
